### PR TITLE
Update alignment result object and return >1 alignments

### PR DESCRIPTION
**Pull request by bow**
This is a pull request following the discussion in #1.

Aside from various internal refactoring, two main changes are proposed here:
1. Updating the return type of the `aligner` function from a tuple of two items into `AlignmentResult`, a namedtuple that contains not only the alignment result but also alignment coordinates, gaps and mismatch counts, and alignment score.
2. Updating the number of items returned from `aligner`. The default is still to return 1 item, but now it returns a list of `AlignmentResult` objects instead of a single tuple. This can be controlled via the `max_hits` parameter supplied to `aligner`.

I'm also proposing a few more user-facing updates (not applied yet at the time of writing):
- Removing the `BLOSUM62` as the default `matrix` parameter value in `aligner`. Instead, `matrix` should not have any default values.
- Adding an alias to `glocal` method called `semiglobal` or `semi-global` or both. 

No changes has been made to the Cython part. It will be done when the proposed changes to the pure Python API has been deemed sensible.

### CODE REVIEW

**Comment by bow** [comment]
Some quick benchmarks of the tip of this PR branch vs tip of current master.

## Python 2, at 941de63

```
In [1]: %timeit -n100 align.aligner('AATCAAG', 'AATGAATGAGTCAATG', method='glocal', matrix=DNAFULL)
100 loops, best of 3: 2.67 ms per loop
```

## Python 2, at current base master (01ce7ae)

```
In [1]: %timeit -n100 align.aligner('AATCAAG', 'AATGAATGAGTCAATG', method='glocal', matrix=DNAFULL)
100 loops, best of 3: 2.55 ms per loop
```

Not that much change, but it is indeed slower (since the main loop is doing more now). I did not try it in Python 3 since the current master tip does not work Python 3.

**Comment by bow** [comment]
All right, after spending more time with the Cython part, I think we have the Cython version updated as well now. There are more updates (detailed below), but here's the most interesting parts first ~ the benchmarks:

## Python 2, master @ 01ce7ae

```
In [1]: %timeit aligner(seq1, seq2, method="global")
10000 loops, best of 3: 37.7 µs per loop

In [2]: %timeit aligner(seq1, seq2, method="local")
10000 loops, best of 3: 23.3 µs per loop

In [3]: %timeit aligner(seq1, seq2, method="glocal")
10000 loops, best of 3: 32.2 µs per loop

In [4]: %timeit aligner(seq1, seq2, method="global_cfe")
10000 loops, best of 3: 39.5 µs per loop
```

## Python 2, this PR

```
In [1]: %timeit aligner(seq1, seq2, method="global")
10000 loops, best of 3: 33 µs per loop

In [2]: %timeit aligner(seq1, seq2, method="local")
100000 loops, best of 3: 16.9 µs per loop

In [3]: %timeit aligner(seq1, seq2, method="glocal")
10000 loops, best of 3: 28.5 µs per loop

In [4]: %timeit aligner(seq1, seq2, method="global_cfe")
10000 loops, best of 3: 19.1 µs per loop
```

## Python 3, this PR

```
In [1]: %timeit aligner(seq1, seq2, method="global")
10000 loops, best of 3: 42.1 µs per loop

In [2]: %timeit aligner(seq1, seq2, method="local")
10000 loops, best of 3: 22.1 µs per loop

In [3]: %timeit aligner(seq1, seq2, method="glocal")
10000 loops, best of 3: 35 µs per loop

In [4]: %timeit aligner(seq1, seq2, method="global_cfe")
10000 loops, best of 3: 24.8 µs per loop
```

I couldn't run the Python 3 benchmark on current master because the Cython version simply couldn't be used under Python 3. But after making some changes (in this PR), it works fine in Python 3 now. Not sure why it's generally slower there (both Python 2 and 3 use the same source .pyx file), but I think it's still reasonable.

Now for the other updates:
- Aside from making `aligner` return multiple results, I've removed explicit dependency to `Python.h` in the cython file.
- The C-version of aligner can now accept a regular dictionary of the scoring matrix or the strings 'DNAFULL' or 'BLOSUM62'.
- There are some performance tweaks, most notable perhaps is less use of numpy's `argmax` and `max`. Instead, the maximum values are tracked as the alignment matrix is filled.
- The tests now run both C and Python versions explicitly. It uses Cython's `pyximport` to ensure that changes in the Cython code are tested as well.
- I've made some changes to setup.py as well, most notably making the C-generated file dynamic.

And finally, I should still say that the current multiple return values are not all optimal alignments, but rather alignments with different trace starting positions.

And some things I'm not sure about:
- Should the plain text matrix files in `data` be kept?
- Should the DNAFULL matrix be renamed to something else (NUCL, perhaps?) since there is a character for `U` there, which isn't exactly DNA ...

**Comment by brentp** [comment]
I just invited you to the repo so you'll have push permissions. I didn't review these changes in the detail that they deserve, but they look good to me.

**Comment by brentp** [comment]
Thanks for all these improvements!

**Comment by bow** [comment]
Hi @brentp,

Thanks for the invite! I guess this means this is safe to merge? If so, I would like to play around with the `setup.py`, mainly with setting up the numpy dependency. Hopefully it will be followed by a 0.0.3 release to PyPI :).

**Comment by brentp** [comment]
go for it. I'll probably have to do the release to pypi, let me know when it's ready.

**Comment by bow** [comment]
Great :). I'll merge this and also close the linked issue.

On a related note, would you mind enabling the repo on Travis? I have it set up [on my fork](https://travis-ci.org/bow/align), but it's better to have it set up on the main repo as well of course.

**Comment by brentp** [comment]
it's activated on travis. please add yourself to the Authors.

**Pull request merged**
